### ISSUE TITLE
1.1.1.3 Error on startup: Code Failed at:Running UI Thread

### ISSUE THREAD

**Issue by yaffeweb** [NHLGames/NHLGames#157]
NHLGames Bug Report v 1.1.1

Operating system: Microsoft Windows 7 Professional  64 Bits

Form: loaded, 0 games currently on form, Spinner (games) invisible 0/1000, Spinner (stream) invisible 0/1000

Servers: NHLGames IP found (nhl.freegamez.gq), NHL.TV redirection is working (Hosts file tested)

Selected player: MPV

Streamer path: C:\Users\user\Downloads\NHLGames_v1.1.1.2\livestreamer\livestreamer.exe [on form] [exe found]

VLC path: C:\Program Files (x86)\VideoLAN\VLC\vlc.exe [on form] [exe found]

MPC path:  [on form] [exe not found]

MPV path: C:\Users\user\Downloads\NHLGames_v1.1.1.2\mpv\mpv.exe [on form] [exe found]

Console log: 

[19:15:54] Status: Setting updated for 'MpcPath' to ''

[19:15:54] Status: Setting updated for 'ShowScores' to 'True'

[19:15:54] Status: Setting updated for 'ShowLiveScores' to 'True'

[19:15:54] Status: Setting updated for 'ShowSeriesRecord' to 'True'

[19:15:54] Status: Setting updated for 'ShowTodayLiveGamesFirst' to 'True'

[19:15:54] Status: Setting updated for 'SelectedLanguage' to 'English'

[19:15:54] Status: Setting updated for 'SelectedServer' to 'nhl.freegamez.gq'

[19:16:10] Fetching: Game schedule for 2018-01-28 from NHL.tv

[19:16:12] Error: Code failed at: Running UI thread - With exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.EndInvoke(IAsyncResult asyncResult)
   at NHLGames.Utilities.InvokeElement.EndInvokeOf(IAsyncResult asyncResult)

**Comment by yaffeweb** [comment]
Nevermind.. This is not a 1.1.1.3 issue. This is a 1.1.1.2 issue and has been technically resolved since there is a newer version. Sorry!
