### ISSUE TITLE
UI failed red box

### ISSUE THREAD

**Issue by anistii** [NHLGames/NHLGames#178]
tried reinstalling, updating, flushing my dns, shutdown my firewall still getting the error any help would be appreciated thank you 

NHLGames Bug Report v 1.2.0.0

Operating system: Microsoft Windows 7 Professional  64 Bits	
Internet: Connection test succeeded, ping google.com succeeded	
Form: loaded, 0 games currently on form, Spinner (games) invisible 0/1000, Spinner (stream) invisible 0/1000	
Servers: NHLGames IP found (freesports.ddns.net)	
Hosts file: NHL.TV redirection is working (Hosts file tested) Entries: 188.240.208.152 mf.svc.nhl.com; 	
Selected player: MPV	
VLC path:  [on form] [exe not found]	
MPC path:  [on form] [exe not found]	
MPV path: C:\Users\Ani\Desktop\NHL\mpv\mpv.exe [on form] [exe found]

Console log: 	
[21:35:01] Status: Setting updated for 'SelectedLanguage' to 'English'	
[21:35:01] Status: Setting updated for 'MpcPath' to ''	 
[21:35:01] Status: Setting updated for 'VlcPath' to ''	
[21:35:01] Status: Setting updated for 'ShowSeriesRecord' to 'True'	
[21:35:01] Status: Setting updated for 'ShowLiveTime' to 'True'	
[21:35:01] Status: Setting updated for 'ShowTodayLiveGamesFirst' to 'True'	
[21:35:01] Status: Setting updated for 'SelectedServer' to 'freesports.ddns.net'	
[21:35:02] Fetching: Game schedule for 2018-04-11 from NHL.tv	
[21:35:03] Error: Code failed at: Running UI thread - With exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.EndInvoke(IAsyncResult asyncResult)
   at NHLGames.Utilities.InvokeElement.EndInvokeOf(IAsyncResult asyncResult)

**Comment by jwallet** [comment]
already in pr
