### ISSUE TITLE
plz help, no hockey playoffs?

### ISSUE THREAD

**Issue by Sly-guy364LEAFS** [NHLGames/NHLGames#179]
NHLGames Bug Report v 1.2.0.0

Operating system: Microsoft Windows 10 Home 64 Bits	
Internet: Connection test succeeded, ping google.com succeeded	
Form: loaded, 0 games currently on form, Spinner (games) invisible 0/1000, Spinner (stream) invisible 0/1000	
Servers: NHLGames IP found (freesports.ddns.net)	
Hosts file: NHL.TV redirection is working (Hosts file tested) Entries: 127.0.0.1       localhost; ::1             localhost; 0.0.0.1 mssplus.mcafee.com; 188.240.208.152 mf.svc.nhl.com; 	
Selected player: MPV	
Streamer path: C:\Users\Jamie\Downloads\NHLGames_v1.2.0_Complete\livestreamer\livestreamer.exe [on form] [exe found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path:  [on form] [exe not found]	
MPV path: C:\Users\Jamie\Downloads\NHLGames_v1.2.0_Complete\mpv\mpv.exe [on form] [exe found]

Console log: 	
[19:10:27] Status: Setting updated for 'SelectedLanguage' to 'English'	
[19:10:27] Status: Setting updated for 'MpcPath' to ''	
[19:10:27] Status: Setting updated for 'ShowSeriesRecord' to 'True'	
[19:10:27] Status: Setting updated for 'ShowLiveTime' to 'True'	
[19:10:27] Status: Setting updated for 'ShowTodayLiveGamesFirst' to 'True'	
[19:10:27] Status: Setting updated for 'SelectedServer' to 'freesports.ddns.net'	
[19:11:24] Fetching: Game schedule for 2018-04-12 from NHL.tv	
[19:11:27] Error: Code failed at: Running UI thread - With exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.EndInvoke(IAsyncResult asyncResult)
   at NHLGames.Utilities.InvokeElement.EndInvokeOf(IAsyncResult asyncResult)

**Comment by jwallet** [comment]
Upate to the lastest version . See Reddit
