### ISSUE TITLE
Getting this error when trying to stream, any ideas on how to fix?

### ISSUE THREAD

**Issue by ntanenho** [NHLGames/NHLGames#227]
[15:17:42] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'

[15:17:42] MLBAMProxy: Proxy is getting ready

[15:17:43] MLBAMProxy: Proxy server listening on port: 17070

[15:17:46] Fetching: Game schedule for 2018-12-02 from NHL.tv

[15:19:00] Error: Code failed at: Running UI thread - With exception: System.InvalidCastException: Conversion from type 'GameWatchArguments' to type 'String' is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at NHLGames.Utilities.ApplicationSettings.Read[T](SettingsEnum key, Object defaultReturnValue)
   at NHLGames.Controls.GameControl.WatchStream(StreamerTypeEnum streamType)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[15:19:58] Error: Code failed at: Running UI thread - With exception: System.InvalidCastException: Conversion from type 'GameWatchArguments' to type 'String' is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at NHLGames.Utilities.ApplicationSettings.Read[T](SettingsEnum key, Object defaultReturnValue)
   at NHLGames.Controls.GameControl.WatchStream(StreamerTypeEnum streamType)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[15:20:07] Error: Code failed at: Running UI thread - With exception: System.InvalidCastException: Conversion from type 'GameWatchArguments' to type 'String' is not valid.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToString(Object Value)
   at NHLGames.Utilities.ApplicationSettings.Read[T](SettingsEnum key, Object defaultReturnValue)
   at NHLGames.Controls.GameControl.WatchStream(StreamerTypeEnum streamType)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jwallet** [comment]
looks like the app can't read/write the `NHLGames.exe.Config` file
