### ISSUE TITLE
error when opening version 1.4

### ISSUE THREAD

**Issue by helterhaze** [NHLGames/NHLGames#248]
NHLGames Bug Report v 1.4.0.0

Operating system: Microsoft Windows 10 Pro 64 Bits - .Net build 4.0.30319.42000	
Internet: Connection test succeeded, ping google.com succeeded	
Streamer args enabled:--hls-segment-threads=2 --hls-segment-attempts=9 --hls-segment-timeout=10 --hls-timeout=180	
Player args enabled:--cache=50000	
Selected player: MPV	
Streamer path:  [on form] [exe not found]	
VLC path: C:\Program Files\VideoLAN\VLC\vlc.exe [on form] [exe found]	
MPC path:  [on form] [exe not found]	
MPV path: C:\Users\helte\Downloads\NHLGames-v1.4-complete\mpv\mpv.exe [on form] [exe found]

Console log: 	
[15:19:21] Status: Setting updated for 'HOSTNAME' to ''	
[15:19:22] Error: Code failed at: Running UI thread - With exception: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at NHLGames.Utilities.Common.SetHttpWebRequest(String address)
   at NHLGames.Utilities.Common.VB$StateMachine_11_SendWebRequestAsync.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NHLGames.Utilities.Common.VB$StateMachine_14_CheckAppCanRun.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NHLGames.NHLGamesMetro.VB$StateMachine_619_NHLGames_Load.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()	
[15:19:22] MLBAMProxy: Proxy version 1.1.1 is getting ready	
[15:19:22] MLBAMProxy: Proxy will act as a default proxy and won't redirect a domain to another, no sources and/or destination were specified	
[15:19:22] MLBAMProxy: Proxy server listening on port: 8080

**Comment by keithcrogers** [comment]
My error is same as before.  "Media Player not Selected"  when I go to Settings, the Media Player is selected, and the player's .exe file is in the correct folder.  Weird bug.  NHLGames not useable until this error bug is resolved.  Can you help? Here is my log:

[13:36:19] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\lh2ityw3.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:19] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\xj2vi502.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:19] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\0e04khja.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\vduoo1ed.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\coakvaqx.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\hhko0qf3.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\mtnvdi20.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\ovkqzfvc.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\lqx214pg.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\pzehu2kv.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\xqkhr4db.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Status: Setting updated for 'HOSTNAME' to 'freegamez.ga'

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\1aw0dzig.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\e5pzslpd.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:20] Warning: Failed to write app settings. Make sure that NHLGames is inside a folder that your user account has full access, like a folder in your user workspace (Documents) or the root of your hard drive. Exception occured with: An error occurred loading a configuration file: Access to the path 'C:\Program Files (x86)\lrwewqyy.tmp' is denied. (C:\Program Files (x86)\NHLGames.exe.Config)

[13:36:21] Fetching: Game schedule for 2019-04-14 from NHL.tv

[13:36:21] MLBAMProxy: Proxy version 1.1.1 is getting ready

[13:36:21] MLBAMProxy: Proxy server listening on port: 17070

[13:37:02] Error: No media player selected in settings.

[13:38:09] Error: No media player selected in settings.

**Comment by helterhaze** [comment]
My solution/workaround was to go back to version 1.3 which works just fine. I am not sure what the bug is in 1.4.

⁣Get BlueMail for Android ​

**Comment by jwallet** [comment]
@keithcrogers pretty sure you need to run the app as an admin when looking at your log, and you probably need to run go-mlbam-hosts first
