### ISSUE TITLE
RTP Schedule not working past July 30

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#269]
For some reason, July 28-30 games are appearing but as of August 1st there is an exception:

```[17:08:58] System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at NHLGames.Objects.GameManager.VB$StateMachine_5_GetGamesAsync.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NHLGames.Utilities.GameFetcher.VB$StateMachine_5_LoadGames.MoveNext()```

I will investigate (must be some change to the API)

**Comment by NHLGames** [comment]
Fixed in 1.4.2
