### ISSUE TITLE
downloader.cs class and My.Computer.Network.DownloadFile

### ISSUE THREAD

**Issue by jwallet** [NHLGames/NHLGames#75]
i've got this error, like others, when trying to refresh the UI, looks like the server got no more room for like 15 minutes. It might be related to something else.

```vb.net
The operation has timed out at System.Net.WebClient.DownloadFile(Uri address, String fileName) 
at Microsoft.VisualBasic.MyServices.Internal.WebClientCopy.DownloadFile(Uri address, String 
destinationFileName) at Microsoft.VisualBasic.Devices.Network.DownloadFile(Uri address, String
 destinationFileName, ICredentials networkCredentials, Boolean showUI, Int32 connectionTimeout, 
Boolean overwrite, UICancelOption onUserCancel) at 
Microsoft.VisualBasic.Devices.Network.DownloadFile(String address, String destinationFileName, String 
userName, String password, Boolean showUI, Int32 connectionTimeout, Boolean overwrite, 
UICancelOption onUserCancel) at NHLGames.Utilities.Downloader.DownloadFile(String url, String 
fileName, Boolean checkIfExists, Boolean overwrite, String checkDelay) at 
NHLGames.Utilities.Downloader.DownloadAvailableGames() at 
NHLGames.NHLGamesMetro.LoadGames(DateTime dateTime, Boolean refreshing)
```

```vb.net
System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.IOException: The process cannot access the file 'C:\Users\w1z1k\AppData\Roaming\NHLGames\games.txt' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Microsoft.VisualBasic.MyServices.Internal.WebClientCopy.DownloadFile(Uri address, String destinationFileName)
   at Microsoft.VisualBasic.Devices.Network.DownloadFile(Uri address, String destinationFileName, ICredentials networkCredentials, Boolean showUI, Int32 connectionTimeout, Boolean overwrite, UICancelOption onUserCancel)
   at Microsoft.VisualBasic.Devices.Network.DownloadFile(String address, String destinationFileName, String userName, String password, Boolean showUI, Int32 connectionTimeout, Boolean overwrite, UICancelOption onUserCancel)
   at NHLGames.Utilities.Downloader.DownloadFile(String url, String fileName, Boolean checkIfExists, Boolean overwrite, String checkDelay)
   at NHLGames.Utilities.Downloader.DownloadAvailableGames()
   at NHLGames.NHLGamesMetro.LoadGames(DateTime dateTime, Boolean refreshing)
```

```vb.net
System.Net.WebException: The remote server returned an error: (403) Forbidden. at 
System.Net.WebClient.DownloadFile(Uri address, String fileName) at 
Microsoft.VisualBasic.MyServices.Internal.WebClientCopy.DownloadFile(Uri address, String 
destinationFileName) at Microsoft.VisualBasic.Devices.Network.DownloadFile(Uri address, String 
destinationFileName, ICredentials networkCredentials, Boolean showUI, Int32 connectionTimeout, 
Boolean overwrite, UICancelOption onUserCancel) at 
Microsoft.VisualBasic.Devices.Network.DownloadFile(String address, String destinationFileName, String 
userName, String password, Boolean showUI, Int32 connectionTimeout, Boolean overwrite, 
UICancelOption onUserCancel) at NHLGames.Downloader.DownloadFile(String URL, String fileName, 
Boolean checkIfExists, Boolean overwrite) at NHLGames.Downloader.DownloadAvailableGames() at
NHLGames.NHLGamesMetro.LoadGames(DateTime dateTime)
```

**Comment by jwallet** [comment]
there is an issue in downloader.cs when downloading a file.
  My.Computer.Network.DownloadFile is a poor class. should use HttpWebRequest (or something call like this). with network.dowloadfile we can not even get the webexception and catch it. the exception is handled by another process. so here are the issues : 
- when trying to download a file from the server and it's too long before getting a response = timeout going over the default 10000 value. this can happen if the app already send a web request a the second is ignore
- when refreshing too many timess the game panel. we get a IOException (can not be handle too since it comes from the same class) because it's trying to recreate the same file but it is already games.txt is already open and  another process is writing in it

**Comment by jwallet** [comment]
got fixed
